# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nUser.proto\"z\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x18\n\x04name\x18\x03 \x03(\x0b\x32\n.User.Name\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x1a+\n\x04Name\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\"#\n\x0bUserRecords\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.Userb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USER_NAME = _USER.nested_types_by_name['Name']
_USERRECORDS = DESCRIPTOR.message_types_by_name['UserRecords']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {

  'Name' : _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
    'DESCRIPTOR' : _USER_NAME,
    '__module__' : 'User_pb2'
    # @@protoc_insertion_point(class_scope:User.Name)
    })
  ,
  'DESCRIPTOR' : _USER,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)
_sym_db.RegisterMessage(User.Name)

UserRecords = _reflection.GeneratedProtocolMessageType('UserRecords', (_message.Message,), {
  'DESCRIPTOR' : _USERRECORDS,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:UserRecords)
  })
_sym_db.RegisterMessage(UserRecords)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=14
  _USER._serialized_end=136
  _USER_NAME._serialized_start=93
  _USER_NAME._serialized_end=136
  _USERRECORDS._serialized_start=138
  _USERRECORDS._serialized_end=173
# @@protoc_insertion_point(module_scope)
